version: '3.0'

services:
  mongo:
      restart: always
      container_name: mongo
      hostname: mongo
      image: mongo:3.0.4
      volumes:  
        - ./data/mongo:/data/db:rw
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "27017:27017"
      domainname: mongo

  node-app:
      restart: always
      build: ./node-app
      container_name: node-app
      ports:
        - 8000:8000
      depends_on:
        - mongo

      